site_name: Dependency-Track
site_url: https://docs.dependencytrack.org
copyright: Copyright &copy; Steve Springett

repo_name: DependencyTrack/dependency-track
repo_url: https://github.com/DependencyTrack/dependency-track

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.share

extra:
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/slack
    link: https://dependencytrack.org/slack
  - icon: fontawesome/brands/github
    link: https://github.com/DependencyTrack
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/u/dependencytrack
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DependencyTrack

extra_css:
- stylesheets/extra.css

markdown_extensions:
- admonition
- attr_list
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- tables

plugins:
- search

nav:
- Home: index.md
- Getting Started:
  - Distributions: getting-started/distributions.md
  - Deployment:
    - Docker: getting-started/deployment/docker.md
    - Kubernetes: getting-started/deployment/kubernetes.md
    - Executable WAR: getting-started/deployment/exewar.md
  - Initial Startup: getting-started/initial-startup.md
  - Configuration: getting-started/configuration.md
  - Database Support: getting-started/database-support.md
  - Monitoring: getting-started/monitoring.md
