site_name: Dependency-Track
site_url: https://docs.dependencytrack.org
copyright: Copyright &copy; Steve Springett

repo_name: DependencyTrack/dependency-track
repo_url: https://github.com/DependencyTrack/dependency-track

theme:
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.share

extra:
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/slack
    link: https://dependencytrack.org/slack
  - icon: fontawesome/brands/github
    link: https://github.com/DependencyTrack
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/u/dependencytrack
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DependencyTrack

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- tables

plugins:
- search

nav:
- Home: index.md

