name: Build CI

on:
  push:
    branches:
      - 'master'          # Default branch
      - '[0-9]+.[0-9]+.x' # Release branches
  pull_request:
    branches:
      - 'master'          # Default branch
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
      publish-container: ${{ github.ref == 'refs/heads/master' }}
    secrets:
      registry-0-usr: ${{ github.repository_owner }}
      registry-0-psw: ${{ secrets.GITHUB_TOKEN }}
